
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Users/marci/AppData/Local/vcpkg/downloads/tools/cmake-3.27.1-windows/cmake-3.27.1-windows-i386/share/cmake-3.27/Modules/CMakeDetermineSystem.cmake:206 (message)"
      - "CMakeLists.txt:2 (project)"
    message: |
      The target system is: Windows - 10.0.19045 - AMD64
      The host system is: Windows - 10.0.19045 - AMD64
...
